const colors = {
  black: '#000',
  themeBackground: '#FFFFFF',
  iconColor: '#333333',
  primary: '#febb2c',
  iconPink: '#d83765',
  radioColor: '#FFF',
  radioOuterColor: '#d83765',
  spinnerColor: '#febb2c',
  orderComplete: '#518ef8',
  orderUncomplete: '#f14336',
  horizontalLine: '#B8B8B8',
  buttonBackground: '#febb2c',
  buttonText: '#FFF',
  buttonBackgroundPink: '#febb2c',
  buttonTextPink: '#FFF',
  textErrorColor: '#FA7751',
  headerBackground: '#FFF',
  headerText: '#2a2a2a',
  fontMainColor: '#000',
  fontSecondColor: '#FFFFFF',
  cartContainer: '#FFF',
  placeHolderColor: '#a5a5a5',
  lightBackground: '#f8f9fa',
  yellowishOrange: '#fff1d4',
  lightWhite: '#FCFCFC',
  primaryBlack: '#0b0b0b',
  background: '#ffffff',
  blueColor: '#00b9c6',
  orange: '#CD5211',
  primaryLightBlue: '#0cc8d5',
};

export default colors;
